### ISSUE TITLE
404

### ISSUE THREAD

**Issue by chasm** [willclarktech/apollo-redux-server#2]
Have the app up and running, but http://localhost:3000 returns a 404. Is there some other URL I should be using?

Here's what I see in the console:

```sh
$ yarn start
yarn start v0.21.3
$ nodemon src/index.js --watch src --exec babel-node
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/aries/Workspace/charity/apollo-redux-server/src/**/*
[nodemon] starting `babel-node src/index.js`
koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md src/koa/server.js:48:5
koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md src/koa/server.js:52:5
koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md src/koa/server.js:53:5
🏃🏃🏃 Server is running on localhost:3000
GET / 404 6.681 ms - 9
GET /favicon.ico 404 1.913 ms - 9
GET / 404 0.714 ms - 9
GET / 404 0.873 ms - 9
GET / 404 1.438 ms - 9
```

**Comment by willclarktech** [comment]
Yep, graphiql is at `GET /graphql`, and graphql requests should go to `POST /graphql`.

You can see the other routes (currently just for authentication) here:
https://github.com/willclarktech/apollo-redux-server/blob/master/src/koa/router.js
https://github.com/willclarktech/apollo-redux-server/blob/master/src/koa/server.config.js

**Comment by chasm** [comment]
Ah, yes, I saw those. Was pretty sure there was no root route at /. Thanks for the clarification.

**Comment by willclarktech** [comment]
I don't have a settled view so far on the best way to do the routes, and I'm definitely considering giving the graphiql and graphql endpoints different names. It might make most sense to have graphql directly on `/` since that's where the main functionality is.

**Comment by chasm** [comment]
Actually, what would help a lot is some sample queries and an explanation of how to send them. I'm using Paw (am on a Mac) and am reading up on Apollo now and looking at the data. I'll figure it out, but a sample would be helpful for users.

**Comment by willclarktech** [comment]
Good idea. graphiql is the easiest way to send queries and mutations that don't require authentication, just `GET /graphql` for the interface. I've only recently finished the authentication stuff with GitHub and JWTs, so haven't updated the docs yet, but for now here's a brief overview:

1. Register an OAuth application with GitHub with a callback URL of `http://localhost:3000/auth/github/` and add the details to the `.env` file.
1. If you `GET /auth/github` (in a browser) you'll be redirected to authenticate with GitHub, which will send a code back to the server, which the server then exchanges for an access token, which it can use to get user details from GitHub.
1. The server then creates a JWT, and redirects to the client, passing the JWT in the url. Without a client app running, this obviously won't load a page, but you can extract the JWT from the url in your browser.
1. Now you can send the JWT along with your graphql requests and you'll be authenticated so you can access protected routes. The preferred way to send JWTs seems to be by setting the `Authorization` header to `Bearer xxx.xxx.xxx` where `xxx.xxx.xxx` is the JWT, but the `koa-jwt` middleware checks a few different ways. graphiql currently doesn't support headers, but Paw should be good.

**Comment by chasm** [comment]
Duh. I forgot all about registering the app with GitHub (and I've done this before). I'll try that tomorrow. Thanks!

**Comment by willclarktech** [comment]
I've moved graphiql to `/graphiql`, but kept graphql at `/graphql` for clarity rather than moving it to `/`.
